language: erlang
notifications:
  email: martin@wiso.cz
otp_release:
  - 19.3
script: rebar get-deps compile eunit
before_install:
    pip install --user codecov
after_success:
  - bin/covertool -cover _build/test/cover/eunit.coverdata -appname lager_humio_backend -output cobertura.xml
  - codecov
